# Site settings
title: Welcome | 尹正飞的博客 
email: 657812595@qq.com 
description: > # this means to ignore newlines until "baseurl:"
 Java码农一个
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yzhengfei.github.io" # the base hostname & protocol for your site
github: yzhengfei 

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'

# Build settings
#markdown: kramdown
markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

sass:
  style: compressed
gems:
  - jekyll-sitemap
baidu_analytics: true
